
# add links to admin tools
update block_content__body
  set body_value = '<h2>Admin Tools</h2>\r\n<ul style=\"margin: 0 0 3px 0;\">\r\n	<li><a href=\"/user-account-administration-tool\" style=\"font-weight:bold\" title=\"Review user accounts with ability to activate/block or change roles.\">User Account Administration Tool</a> - Review and Manage User Accounts</li>\r\n	<li><a href=\"/partner-application-administration-tool\" style=\"font-weight:bold\" title=\"Review Partner Applications\">Partner Application Administration Tool</a> - Review Partner Applications</li>\r\n	<li><a href=\"/AddPartner\" style=\"font-weight:bold\" title=\"Add or Edit ICRP Partner\">Add / Edit Partner</a> - Add or Edit ICRP Partner</li>\r\n	<li><a href=\"/AddFundingOrg\" style=\"font-weight:bold\" title=\"Add ICRP Funding Organization\">Add / Edit Funding Organization</a> - Add or Edit ICRP Funding Organization</li>\r\n	<li><a href=\"/AddInstitution\" style=\"font-weight:bold\" title=\"Add or Edit Institution\">Add / Edit Institution</a> - Add or Edit Institution</li>\r\n	<li><a href=\"/ImportInstitutions\" style=\"font-weight:bold\" title=\"Batch import host institutions\">Import Institutions</a> - Batch import host institutions</li>\r\n	<li><a href=\"/MergeInstitutions\" style=\"font-weight:bold\" title=\"Merge institutions\">Merge Institutions</a> - Merge two institutions</li>\r\n	<li><a href=\"/ImportCollaborators\" style=\"font-weight:bold\" title=\"Batch import collaborators\">Import Collaborators</a> - Batch import collaborators</li>\r\n	<li><a href=\"/DataUploadTool\" style=\"font-weight:bold\" title=\"Load Partner data to staging\">Partner Data Upload Tool</a> - Load Partner data to staging</li>\r\n</ul>'
  where entity_id = 15;

# add links to admin tools (update revision)
update block_content_revision__body
  set body_value = '<h2>Admin Tools</h2>\r\n<ul style=\"margin: 0 0 3px 0;\">\r\n	<li><a href=\"/user-account-administration-tool\" style=\"font-weight:bold\" title=\"Review user accounts with ability to activate/block or change roles.\">User Account Administration Tool</a> - Review and Manage User Accounts</li>\r\n	<li><a href=\"/partner-application-administration-tool\" style=\"font-weight:bold\" title=\"Review Partner Applications\">Partner Application Administration Tool</a> - Review Partner Applications</li>\r\n	<li><a href=\"/AddPartner\" style=\"font-weight:bold\" title=\"Add or Edit ICRP Partner\">Add / Edit Partner</a> - Add or Edit ICRP Partner</li>\r\n	<li><a href=\"/AddFundingOrg\" style=\"font-weight:bold\" title=\"Add ICRP Funding Organization\">Add / Edit Funding Organization</a> - Add or Edit ICRP Funding Organization</li>\r\n	<li><a href=\"/AddInstitution\" style=\"font-weight:bold\" title=\"Add or Edit Institution\">Add / Edit Institution</a> - Add or Edit Institution</li>\r\n	<li><a href=\"/ImportInstitutions\" style=\"font-weight:bold\" title=\"Batch import host institutions\">Import Institutions</a> - Batch import host institutions</li>\r\n	<li><a href=\"/MergeInstitutions\" style=\"font-weight:bold\" title=\"Merge institutions\">Merge Institutions</a> - Merge two institutions</li>\r\n	<li><a href=\"/ImportCollaborators\" style=\"font-weight:bold\" title=\"Batch import collaborators\">Import Collaborators</a> - Batch import collaborators</li>\r\n	<li><a href=\"/DataUploadTool\" style=\"font-weight:bold\" title=\"Load Partner data to staging\">Partner Data Upload Tool</a> - Load Partner data to staging</li>\r\n</ul>'
  where entity_id = 15;