event_group_color:
  partner_news_and_announcements: ROYALBLUE
  annual_meetings: DARKCYAN
  communications_and_membership: TURQUOISE
  cso_and_coding: DARKORANGE
  evaluations_and_analyses: OLIVEDRAB
  partner_operations: MEDIUMVIOLETRED
  website_and_database: INDIANRED
  funding_opportunities: CRIMSON
_core:
  default_config_hash: YhpQ_567STNeTlcvsyvHSAfEq89eReOCjgLA83bBC3k
