<?php


function db_admin_theme($existing, $type, $theme, $path) {
  return [
    'funding_organizations' => [
      'variables' => [],
    ],

    'partners' => [
      'variables' => [],
    ],

    'update_organization_name' => [
      'variables' => [
        'fields' => []
      ],
    ],

    'institutions' => [
      'variables' => [],
    ],

    'merge_institutions' => [
      'variables' => [],
    ],

  ];
}