<?php

/**
 * @file
 * ICRP DB Project View module.
 */


function db_project_view_theme($existing, $type, $theme, $path) {
  return array(
    'db_project_view' => array(
      'variables' => array(
          'title' => NULL,
          'piFirstName' => NULL,
          'piLastName' => NULL,
          'institution' => NULL,
          'city' => NULL,
          'state' => NULL,
          'country' => NULL,
          'awardCode' => NULL,
          'fundingOrg' => NULL,
          'budgetStartDate' => NULL,
          'budgetEndDate' => NULL,
          'projectStartDate' => NULL,
          'projectEndDate' => NULL,
          'fundingMechanism' => NULL,
          'techAbstract' => NULL,
          'publicAbstract' => NULL,
          'cancerTypes' => NULL,
          'csoAreas' => NULL
        ),
    ),
  );
}