services:
  icrp:
    build: 
      context: "."
      dockerfile: "docker/icrp.dockerfile"
    ports:
      - "8000:80"
    volumes:
      - "./sites/default/settings.php:/var/www/html/sites/default/settings.php"
      - "./themes/bootstrap_subtheme:/var/www/html/themes/bootstrap_subtheme"
      - "./modules/custom:/var/www/html/modules/custom"
    environment:
      HOSTNAME: "localhost"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "icrp"
      MYSQL_USER: "icrp"
      MYSQL_PASSWORD: "icrp"
    cap_add:
      - SYS_NICE
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "icrp-1234"
 
    
