services:
  icrp:
    build: 
      context: "."
      dockerfile: "docker/icrp.dockerfile"
    ports:
      - "8000:80"
    volumes:
      - "./sites/default:/var/www/html/sites/default"
      - "./data:/var/www/html/data"
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - "3307:3306"
      - "33061:33060"
    environment: 
      MYSQL_ROOT_PASSWORD: example-root-password