content_access_node_type:
  basic_node: 'a:2:{s:8:"view_own";a:5:{i:0;s:9:"anonymous";i:1;s:13:"authenticated";i:2;s:13:"administrator";i:3;s:7:"manager";i:4;s:7:"partner";}s:4:"view";a:5:{i:0;s:9:"anonymous";i:1;s:13:"authenticated";i:2;s:13:"administrator";i:3;s:7:"manager";i:4;s:7:"partner";}}'
