module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  autologout: 0
  automated_cron: 0
  backup_migrate: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  ckeditor: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  colors: 0
  comment: 0
  config: 0
  contact: 0
  content_access: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  data_load: 0
  datatables: 0
  datetime: 0
  datetime_range: 0
  db_admin: 0
  db_cancer_type_list: 0
  db_email_results: 0
  db_export_results: 0
  db_map: 0
  db_project_view: 0
  db_search: 0
  db_search_api: 0
  dblog: 0
  devel: 0
  ds_extras: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  email_registration: 0
  embed: 0
  entity: 0
  entity_embed: 0
  entity_notification: 0
  examples: 0
  faq: 0
  field: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  fullcalendar: 0
  fullcalendar_legend: 0
  fullcalendar_options: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  icrp: 0
  icrp_custom_conditions: 0
  image: 0
  inline_form_errors: 0
  layout_discovery: 0
  libraries: 0
  library: 0
  link: 0
  linkit: 0
  media_entity: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  partnership_import: 0
  path: 0
  plugin_type_example: 0
  quickedit: 0
  rdf: 0
  recovery_pass: 0
  redirect: 0
  responsive_image: 0
  rules: 0
  search: 0
  search_exclude: 0
  search_kint: 0
  security_review: 0
  serialization: 0
  shortcut: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tracker: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  user_import: 0
  views_bootstrap: 0
  views_templates: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  webform_views: 0
  yaml_content: 0
  ds: 1
  extlink: 1
  forum: 1
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  bootstrap_subtheme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
