extlink_include: ''
extlink_exclude: ''
extlink_alert_text: ''
extlink_alert: false
extlink_target: true
extlink_subdomains: false
extlink_mailto_class: '0'
extlink_img_class: false
extlink_class: ext
extlink_css_exclude: ''
extlink_css_explicit: ''
extlink_label: '(link is external)'
extlink_mailto_label: '(link sends email)'
extlink_target_no_override: false
extlink_nofollow: false
extlink_follow_no_override: false
