unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: true
element_name: url
time_limit: 1
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  contact_message_feedback_form: true
  contact_message_personal_form: true
  node_article_form: false
  node_basic_node_form: false
  node_events_form: false
  node_faq_form: false
  node_forum_form: false
  node_organization_form: false
  node_page_form: false
  node_partner_page_form: false
  node_slideshow_form: false
  node_testimonial_form: false
  comment_comment_form: false
  comment_comment_forum_form: false
_core:
  default_config_hash: jEhrePho9bAz_8-E-zPMXvlx4knpphzUdaiQJX-xc8Q
