<?php

use Symfony\Component\Debug\ErrorHandler;
use Symfony\Component\Debug\ExceptionHandler;

ErrorHandler::register();
ExceptionHandler::register();

function data_load_theme($existing, $type, $theme, $path) {
    return [
        'data_load' => [
            'variables' => [],
        ],
        'import_institutions' => [
            'variables' => [],
        ],
        'import_collaborators' => [
            'variables' => [],
        ],
    ];
}