<?php

require_once __DIR__ . '/vendor/autoload.php';

\Symfony\Component\Debug\ErrorHandler::register();
\Symfony\Component\Debug\ExceptionHandler::register();

function data_load_theme($existing, $type, $theme, $path) {
    return [
        'data_upload_tool' => [
            'variables' => [],
        ],
        'import_institutions' => [
            'variables' => [],
        ],
        'import_collaborators' => [
            'variables' => [],
        ],
    ];
}