
--
-- Create ICRP Events Block
--

INSERT INTO `block_content` VALUES (31,31,'basic','d85520f7-c780-4117-b85b-5c906e478095','en');
INSERT INTO `block_content__body` VALUES ('basic',0,31,31,'en',0,'<p>Content ICRP’s mission is to improve access to information about global cancer research funding and enable cancer research funding organizations to work collaboratively to address common challenges.</p>\r\n\r\n<p>Our <strong>annual meetings</strong> are a great opportunity to connect with other cancer research funders, explore options for collaborative funding and exchange innovative ideas. Registration is free – please see below for information about past and forthcoming meetings.</p>\r\n\r\n<h5>2019 Annual Meeting</h5>\r\n\r\n<p>Further information about the 2019 annual meeting will be posted here during May 2018. To register your interest and be added to the mailing list, please <a href=\"/contact-us?type-of-issue=Sign%20Up%20for%20Newsletter\">contact us</a>.</p>\r\n','','full_html');
INSERT INTO `block_content_field_data` VALUES (31,31,'basic','en','ICRP Events',1522944060,1,1);
INSERT INTO `block_content_field_revision` VALUES (31,31,'en','ICRP Events',1522944060,1,1);
INSERT INTO `block_content_revision` VALUES (31,31,'en',NULL,1522944060,NULL);
INSERT INTO `block_content_revision__body` VALUES ('basic',0,31,31,'en',0,'<p>Content ICRP’s mission is to improve access to information about global cancer research funding and enable cancer research funding organizations to work collaboratively to address common challenges.</p>\r\n\r\n<p>Our <strong>annual meetings</strong> are a great opportunity to connect with other cancer research funders, explore options for collaborative funding and exchange innovative ideas. Registration is free – please see below for information about past and forthcoming meetings.</p>\r\n\r\n<h5>2019 Annual Meeting</h5>\r\n\r\n<p>Further information about the 2019 annual meeting will be posted here during May 2018. To register your interest and be added to the mailing list, please <a href=\"/contact-us?type-of-issue=Sign%20Up%20for%20Newsletter\">contact us</a>.</p>\r\n','','full_html');

--
-- Create External Resources Block
--

INSERT INTO `block_content` VALUES (32,32,'basic','c8e14978-d9d3-41fc-81de-c2757eebe954','en');
INSERT INTO `block_content__body` VALUES ('basic',0,32,32,'en',0,'<p>ICRP’s aim is to promote international cancer research collaboration and avoid duplication. We collaborate with many other organizations internationally to improve outcomes for cancer patients. Use the links below to find out more.</p>\r\n\r\n<h5>Cancer prevention and cancer control:</h5>\r\n\r\n<ul>\r\n	<li><a href=\"https://www.uicc.org/who-we-are/about-us\" target=\"_blank\">Union for International Cancer Control (UICC)</a></li>\r\n	<li><a href=\"https://www.iarc.fr/\" target=\"_blank\">International Agency for Research on Cancer (IARC)</a></li>\r\n</ul>\r\n\r\n<h5>Cancer Screening</h5>\r\n\r\n<ul>\r\n	<li><a href=\"https://healthcaredelivery.cancer.gov/icsn/\" target=\"_blank\">International Cancer Screening Network (ICSN)</a></li>\r\n</ul>\r\n\r\n<h5>Cancer Trials</h5>\r\n\r\n<ul>\r\n<li><a href=\"http://www.irci.info/\" target=\"_blank\">International Rare Cancers Clinical Trials Initiative</a></li>\r\n</ul>\r\n','','full_html');
INSERT INTO `block_content_field_data` VALUES (32,32,'basic','en','External Resources',1522948467,1,1);
INSERT INTO `block_content_field_revision` VALUES (32,32,'en','External Resources',1522948467,1,1);
INSERT INTO `block_content_revision` VALUES (32,32,'en',NULL,1522948467,NULL);
INSERT INTO `block_content_revision__body` VALUES ('basic',0,32,32,'en',0,'<p>ICRP’s aim is to promote international cancer research collaboration and avoid duplication. We collaborate with many other organizations internationally to improve outcomes for cancer patients. Use the links below to find out more.</p>\r\n\r\n<h5>Cancer prevention and cancer control:</h5>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ul>\r\n	<li><a href=\"https://www.uicc.org/who-we-are/about-us\" target=\"_blank\">Union for International Cancer Control (UICC)</a></li>\r\n	<li><a href=\"https://www.iarc.fr/\" target=\"_blank\">International Agency for Research on Cancer (IARC)</a></li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<h5>Cancer Screening</h5>\r\n\r\n<ul>\r\n	<li><a href=\"https://healthcaredelivery.cancer.gov/icsn/\" target=\"_blank\">International Cancer Screening Network (ICSN)</a></li>\r\n</ul>\r\n\r\n<h5>Cancer Trials</h5>\r\n\r\n<ul>\r\n	<li><a href=\"http://www.irci.info/\" target=\"_blank\">International Rare Cancers Clinical Trials Initiative</a></li>\r\n</ul>\r\n','','full_html');
