--
-- Update Partner Welcome Block
--

UPDATE `block_content__body`
    SET body_value = '<p>As a partner, you can use the resources and information available to all members of our funding organizations. Use the links below to update you user profile, access the full partner dataset or find resources in the partner library.</p>\r\n\r\n<h2>User Tools</h2>\r\n\r\n<ul style=\"margin: 0 0 3px 0;\">\r\n	<li><a href=\"/my-profile\" style=\"font-weight:bold\">Update Profile</a> - Update your user profile and password</li>\r\n	<!--\r\n	<li><a href=\"/sites/default/files/downloads/ICRPDataDictionary.pdf\" style=\"font-weight:bold\">Data Resources</a> - View CSO Codes, Partner Data Caveats, Training Guides, Data Upload Status reports and the ICRP Data Dictionary</li>\r\n	-->\r\n	<li><a href=\"/db_search\" style=\"font-weight:bold\">Search &amp; Analysis</a> - Search the ICRP database and export or graph the results</li>\r\n	<li><a href=\"/data-upload-review\" style=\"font-weight:bold\">Data Review Tool</a> - Use this to review your latest data upload before it is loaded to the ICRP live database</li>\r\n</ul>\r\n\r\n<h2>Data Tools</h2>\r\n\r\n<ul style=\"margin: 0 0 3px 0;\">\r\n	<li><a href=\"/partners\" style=\"font-weight:bold\">ICRP Partners and Funding Organizations</a> - View current ICRP Partners and Funding Organizations</li>\r\n<li><a href=\"/cso\" style=\"font-weight:bold\">CSO</a> - View CSO Codes</li>\r\n	<li><a href=\"/ICRPDataCaveats\" style=\"font-weight:bold\">ICRP Data Caveats</a> - View Partner Data Caveats</li>\r\n	<li><a href=\"/sites/default/files/downloads/ICRPDataDictionary.pdf\" style=\"font-weight:bold\">Data Dictionary</a> - View ICRP Data Dictionary</li>\r\n	<li><a href=\"/ExportLookupTable\" style=\"font-weight:bold\">Export Lookup Table</a> - Export ICRP Data Lookup Tables</li>\r\n	<li><a href=\"/uploadStatusReport\" style=\"font-weight:bold\">Data Upload Status Report</a> - View Partner Data Upload Status Report</li>\r\n</ul>\r\n\r\n<h2>Communications Tools</h2>\r\n\r\n<ul>\r\n	<li><strong><a href=\"/forum/6\">Partnership Forum</a></strong> - ICRP Partnership Forum</li>\r\n	<li><a href=\"https://twitter.com/icrpartners1?ref_src=twsrc%5Etfw\" style=\"font-weight:bold\">Twitter</a> - sign up to our Twitter feed</li>\r\n	<li><a href=\"/library\" style=\"font-weight:bold\">Library</a> - Access resources stored within the ICRP Library</li>\r\n</ul>\r\n'
    WHERE entity_id = 14;

UPDATE `block_content_revision__body`
    SET body_value = '<p>As a partner, you can use the resources and information available to all members of our funding organizations. Use the links below to update you user profile, access the full partner dataset or find resources in the partner library.</p>\r\n\r\n<h2>User Tools</h2>\r\n\r\n<ul style=\"margin: 0 0 3px 0;\">\r\n	<li><a href=\"/my-profile\" style=\"font-weight:bold\">Update Profile</a> - Update your user profile and password</li>\r\n	<!--\r\n	<li><a href=\"/sites/default/files/downloads/ICRPDataDictionary.pdf\" style=\"font-weight:bold\">Data Resources</a> - View CSO Codes, Partner Data Caveats, Training Guides, Data Upload Status reports and the ICRP Data Dictionary</li>\r\n	-->\r\n	<li><a href=\"/db_search\" style=\"font-weight:bold\">Search &amp; Analysis</a> - Search the ICRP database and export or graph the results</li>\r\n	<li><a href=\"/data-upload-review\" style=\"font-weight:bold\">Data Review Tool</a> - Use this to review your latest data upload before it is loaded to the ICRP live database</li>\r\n</ul>\r\n\r\n<h2>Data Tools</h2>\r\n\r\n<ul style=\"margin: 0 0 3px 0;\">\r\n	<li><a href=\"/partners\" style=\"font-weight:bold\">ICRP Partners and Funding Organizations</a> - View current ICRP Partners and Funding Organizations</li>\r\n<li><a href=\"/cso\" style=\"font-weight:bold\">CSO</a> - View CSO Codes</li>\r\n	<li><a href=\"/ICRPDataCaveats\" style=\"font-weight:bold\">ICRP Data Caveats</a> - View Partner Data Caveats</li>\r\n	<li><a href=\"/sites/default/files/downloads/ICRPDataDictionary.pdf\" style=\"font-weight:bold\">Data Dictionary</a> - View ICRP Data Dictionary</li>\r\n	<li><a href=\"/ExportLookupTable\" style=\"font-weight:bold\">Export Lookup Table</a> - Export ICRP Data Lookup Tables</li>\r\n	<li><a href=\"/uploadStatusReport\" style=\"font-weight:bold\">Data Upload Status Report</a> - View Partner Data Upload Status Report</li>\r\n</ul>\r\n\r\n<h2>Communications Tools</h2>\r\n\r\n<ul>\r\n	<li><strong><a href=\"/forum/6\">Partnership Forum</a></strong> - ICRP Partnership Forum</li>\r\n	<li><a href=\"https://twitter.com/icrpartners1?ref_src=twsrc%5Etfw\" style=\"font-weight:bold\">Twitter</a> - sign up to our Twitter feed</li>\r\n	<li><a href=\"/library\" style=\"font-weight:bold\">Library</a> - Access resources stored within the ICRP Library</li>\r\n</ul>\r\n'
    WHERE entity_id = 14;

--
-- Update FAQ Node (entity_id 167)
--

UPDATE `node__body`
    SET body_value = '<p>We estimate that our database covers around 60-70% of world cancer research funding. We welcome applications for <a href=\"/become-a-partner\">membership</a> from cancer research funders worldwide to enhance our coverage.</p>\r\n\r\n<p>Data on the ICRP website is updated regularly, according to our partners’ funding and data collection schedules. Data for the most recent calendar years may be incomplete. For details on recent uploads visit our <a href=\"/partners\">ICRP Partners and Funding Organizations</a> page</p>\r\n\r\n<p>&nbsp;</p>\r\n'
    WHERE entity_id = 167;

UPDATE `node_revision__body`
    SET body_value = '<p>We estimate that our database covers around 60-70% of world cancer research funding. We welcome applications for <a href=\"/become-a-partner\">membership</a> from cancer research funders worldwide to enhance our coverage.</p>\r\n\r\n<p>Data on the ICRP website is updated regularly, according to our partners’ funding and data collection schedules. Data for the most recent calendar years may be incomplete. For details on recent uploads visit our <a href=\"/partners\">ICRP Partners and Funding Organizations</a> page</p>\r\n\r\n<p>&nbsp;</p>\r\n'
    WHERE entity_id = 167;
