<?php

/**
 * @file
 * ICRP DB Project View module.
 */

// require_once __DIR__ . '/vendor/autoload.php';

function db_map_theme($existing, $type, $theme, $path) {
  return [
    'db_map' => [
      'variables' => []
    ],
    'db_people_map' => [
      'variables' => [
        'funding_details' => NULL,
        'pi_count' => NULL,
        'project_id' => NULL
      ]
    ],
    'db_layer_map' => [
      'variables' => [
        'layers' => NULL,
      ]
    ],
  ];
}
