# Schema for the configuration files of the node module.

external_entities.type.*:
  type: config_entity
  label: 'External entity type'
  mapping:
    label:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    read_only:
      type: boolean
      label: 'Read only'
    field_mappings:
      type: sequence
      label: 'Field mappings'
      sequence:
        type: string
        label: 'Field mapping'
    endpoint:
      type: string
      label: 'Endpoint'
    client:
      type: string
      label: 'Storage client'
    format:
      type: string
      label: 'Format'
    pager_settings:
      type: mapping
      label: 'Pager settings'
      mapping:
        default_limit:
          type: string
          label: 'Default limit'
        page_parameter:
          type: string
          label: 'Page parameter'
        page_parameter_type:
          type: string
          label: 'Page parameter type'
        page_size_parameter:
          type: string
          label: 'Page size parameter'
        page_size_parameter_type:
          type: string
          label: 'Page size parameter type'
    api_key_settings:
      type: mapping
      label: 'API key settings'
      mapping:
        header_name:
          type: string
          label: 'API key header name'
        key:
          type: string
          label: 'API key'
    parameters:
      type: mapping
      label: 'Parameters'
      mapping:
        list:
          type: sequence
          sequence:
            type: sequence
            label: 'List parameter'
            sequence:
              type: string
        single:
          type: sequence
          sequence:
            type: sequence
            label: 'Single load parameter'
            sequence:
              type: string
