# Before running docker-compose, ensure that the the following resources exist: 
#  - ./run/drupal/    ## contains all drupal files (mounted under document root)
#  - ./run/icrp.sql   ## contains a .sql dump of the current database
#  - ./run/ssl/crt    ## SSL certificate
#  - ./run/ssl/key    ## SSL key 
#
# After running docker-compose, the deployment script should:
#  - restore the database from the .sql dump
#  - rebuild the drupal cache

version: '3' 
services:
  drupal:
    build:
      context: ./build 
      dockerfile: drupal.prod.dockerfile
    container_name: icrp-drupal
    depends_on:
     - db
    links:
     - db:database
    ports:
      - '80:80'
      - '443:443' 
    volumes:
      - ./run/drupal:/var/www/html
      - ./run/ssl/crt:/etc/pki/tls/certs/localhost.crt:ro
      - ./run/ssl/key:/etc/pki/tls/private/localhost.key:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
  db:
    image: 'mysql:latest'
    container_name: icrp-mysql
    expose:
      - '3306'
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=temporary-root-password
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - /var/lib/mysql
      - ./run/icrp.sql:/tmp/icrp.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-sp$$MYSQL_ROOT_PASSWORD'] 
      interval: 2s
      timeout: 10s
      retries: 12
