# Configuration schema for the Libraries API module.

libraries.settings:
  type: config_object
  label: 'Libraries API settings'
  mapping:
    definition:
      type: mapping
      label: 'Library definition settings'
      mapping:
        local:
          type: mapping
          label: 'Local'
          mapping:
            path:
              type: path
              label: 'Local path'
        remote:
          type: mapping
          title: 'Remote'
          mapping:
            enable:
              type: boolean
              label: 'Enable remote fetching of library definitions'
            urls:
              type: sequence
              label: 'A list of remote library registry URLs'
              sequence:
                type: uri
                label: 'The URL of a remote library registry'
