<?php

/**
 * @file
 * Install, update and uninstall functions for the YAML Form Test module.
 */

use Drupal\yamlform\Entity\YamlForm;
use Drupal\Core\Url;

module_load_include('inc', 'yamlform', 'includes/yamlform.update');

/**
 * Implements hook_install().
 */
function yamlform_test_install() {
  // Update 'Test: Handler: Remote post' URLs.
  /** @var \Drupal\yamlform\YamlFormInterface $remote_post_yamlform */
  $remote_post_yamlform = YamlForm::load('test_handler_remote_post');

  /** @var \Drupal\yamlform\Plugin\YamlFormHandler\RemotePostYamlFormHandler $remote_post_handler */
  $remote_post_handler = $remote_post_yamlform->getHandler('remote_post');
  $remote_post_configuration = $remote_post_handler->getConfiguration();

  $remote_post_configuration['settings']['insert_url'] = Url::fromRoute('yamlform_test.remote_post', ['type' => 'insert'])->setAbsolute()->toString();
  $remote_post_configuration['settings']['update_url'] = Url::fromRoute('yamlform_test.remote_post', ['type' => 'update'])->setAbsolute()->toString();
  $remote_post_configuration['settings']['delete_url'] = Url::fromRoute('yamlform_test.remote_post', ['type' => 'delete'])->setAbsolute()->toString();
  $remote_post_handler->setConfiguration($remote_post_configuration);

  $remote_post_yamlform->save();

  // Set public file upload support for testing.
  $settings_config = \Drupal::configFactory()->getEditable('yamlform.settings');
  $settings_config->set('elements.file_public', TRUE);
  $settings_config->save();
}
