<?php

function bootstrap_subtheme_page_alter(&$page)
{
  global $user;

  $path = drupal_get_path('module', MYMODULE);
  $page['page_bottom']['MYMODULE_js'] = array
  (
    '#markup' => '',
    '#attached' => array
    (
      'js' => array
      (
        array
        (
          'type' => 'file',
          'data' => $path . '/js/MYMODULE.js',
          'group' => JS_LIBRARY,
          'every_page' => TRUE,
        ),
        array
        (
          'type' => 'setting',
          'data' => array('myModule' => array('username' => $user->name)),
        ),
      ),
    ),
  );
}
