<?php

/**
 * @file
 * Primary module hooks for Snippet manager test module.
 */

use Drupal\snippet_manager\SnippetInterface;

/**
 * Implements hook_page_bottom().
 */
function snippet_manager_test_page_bottom(array &$page_bottom) {
  $snippet_id = \Drupal::state()->get('show_snippet');
  if ($snippet_id) {
    $page_bottom['wrapper']['#type'] = 'details';
    $page_bottom['wrapper']['#summary'] = 'snippet';
    /** @var \Drupal\snippet_manager\SnippetViewBuilder $view_builder */
    $view_builder = \Drupal::entityTypeManager()->getViewBuilder('snippet');
    $page_bottom['wrapper']['snippet'] = $view_builder->buildRenderArray($snippet_id);
  }
}

/**
 * Implements hook_snippet_manager_context().
 */
function snippet_manager_test_snippet_context(SnippetInterface $snippet) {
  if ($snippet->id() == 'gamma') {
    return ['foo' => 'Foo'];
  }
}

/**
 * Implements hook_snippet_manager_context_alter().
 */
function snippet_manager_test_snippet_context_alter(array &$context, SnippetInterface $snippet) {
  if ($snippet->id() == 'gamma') {
    $context['bar'] = 'Bar';
  }
}
