<?php
/**
 * @file
 * Hook implementations for the External Entities module.
 */

use Drupal\Component\Utility\Xss;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function external_entities_theme() {
  return [
    'external_entities_add_list' => [
      'variables' => ['external_entity_types' => NULL],
    ],
    'external_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for list of available external entity type templates.
 *
 * Default template: external-entities-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of external entity types.
 */
function template_preprocess_external_entities_add_list(&$variables) {
  $variables['types'] = array();
  if (!empty($variables['external_entity_types'])) {
    foreach ($variables['external_entity_types'] as $type) {
      $variables['types'][$type->id()] = array(
        'type' => $type->id(),
        'add_link' => \Drupal::l($type->label(), new Url('external_entity.add', array('external_entity_type' => $type->id()))),
        'description' => Xss::filterAdmin($type->getDescription()),
      );
    }
  }
}

/**
 * Prepares variables for external entity templates.
 *
 * Default template: external-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the external entity and any
 *     fields attached to the entity. Properties used:
 *     - #external_entity: A \Drupal\external_entities\Entity\ExternalEntity
 *       object.
 *     - #view_mode: The current view mode for this external entity, e.g.
 *       'full' or 'teaser'.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_external_entity(&$variables) {
  $variables['external_entity'] = $variables['elements']['#external_entity'];
  // Helpful $content variable for templates.
  $variables['content'] = array();
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
