<?php

use Drupal\views\Views;

/**
 * Implements hook_theme_registry_alter().
 */
function views_bootstrap_theme_registry_alter(&$theme_registry) {
  $plugins = Views::getPluginDefinitions();
  $path = drupal_get_path('module', 'views_bootstrap');

  foreach ($plugins['style'] as $style) {
    if ($style['provider'] == 'views_bootstrap') {
      $theme = $style['theme'];

      switch ($theme) {
        case 'views_bootstrap_table':
          $theme_registry[$theme]['preprocess functions'][] = 'template_preprocess_views_view_table';
          break;
          
        case 'views_bootstrap_accordion':
          $theme_registry[$theme]['preprocess functions'][] = 'template_preprocess_views_view_accordion';
          break;

        case 'views_bootstrap_carousel':
          $theme_registry[$theme]['preprocess functions'][] = 'template_preprocess_views_view_carousel';
          break;
      }
      
      $theme_registry[$theme]['path'] = $path . '/templates/' . $theme;
      $theme_registry[$theme]['includes'][] = $theme_registry[$theme]['path'] . '/theme.inc';
      $theme_registry[$theme]['preprocess functions'][] = 'template_preprocess_' . $theme;
    }
  }
}
