<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use \Drupal\icrp\Importer\OrganizationRestClient;
use Drupal\views\Plugin\views\PluginBase;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;

/*
 * source: https://www.youtube.com/watch?v=L5x3WqTZPGk
 * @25:58 minutes
 * Overview of rendering flow
 * 1. drupal_render()
 *   2. #pre_render
 *   3. _theme()
 *     4. Theme suggestion hooks
 *     5. Preprocess functions
 *     6. Template is rendered
 *   7. #post_render
 *
 */
/*


function icrp_user_login($account) {
    // We want to redirect user on login.
    $response = new RedirectResponse("mypath");
    $response->send();
    return;
}
*/

/*
function icrp_user_login($account) {

    drupal_Set_message("I control you.");

    $url = "/home";
    $response = new Symfony\Component\HttpFoundation\RedirectResponse($url);
    $response->send();
    return;
}
*/
function icrp_preprocess_menu_local_action(&$variables) {
  //kint($variables);
  //unset($variables['element']);
}

function icrp_preprocess_forums(&$variables) {
  $variables['chris'] = 'Kneisler';
  //drupal_set_message("Added icrp_debug to variables.  See if you can access in twig.");
  //kint($variables);

}
function icrp_preprocess_forum_list(&$variables) {
  //$variables['icrp_debug'] = true;
  //drupal_set_message("Added icrp_debug to variables.  See if you can access in twig.");

  $variables['hello'] = 'World';
  //drupal_set_message("Added chris to variables.  See if you can access in twig.");
  //kint($variables);

}

function icrp_template_preprocess_default_variables_alter(&$variables) {
  $variables['icrp_debug'] = false;
  #$variables['icrp_debug'] = true;
  $variables['is_admin'] = 'Dont know';
  //drupal_set_message("We got something now");
  //var_dump($variables);
}

function icrp_user_format_name_alter(&$name, $account) {
  // Display the user's uid instead of name.
  //kint($account->get('field_first_name')->value);
  /*
  if ($account->id()) {
    $name = t('User @uid', array('@uid' => $account->id()));
  }
  */
}
function icrp_mail($key, &$message, $params) {

  // E-mail formatting will be exactly as below, so do not use indenting!
 $options = array(
    'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'approvedPartnershipApplicationMail':

        $body =
"Dear Partner,

We’re delighted to inform you that your application for membership of the ICRP has been approved. The Operations Manager will be in contact with you shortly and will send your new member’s pack.

With kind regards,

The ICRP team";
          //drupal_set_message($body);
          $message['from'] = \Drupal::config('system.site')->get('mail');
          $message['subject'] = "ICRP Partnership Application - Completed";
          $message['body'][] = Drupal\Core\Mail\MailFormatHelper::htmlToText($body);
          break;
    }
}
/*
function partnerApplicationSubmissionsTable() {
    //First Check to see if there are any Submitted Applications
    //If count is zero, then display all Active Submissions
    $markup = '<h1>Partner Application Administration Tool</h1>';
    $markup .= '<table id="partner-application-table" class="table table-striped table-bordered table-condensed cols-6 sticky-enabled">
  <thead>
  <tr>
    <th>Organization</th>
    <th>City</th>
    <th>Country</th>
    <th>Email</th>
    <th>Date Submitted</th>
    <th>Review Data</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Universal Cancer Research</td>
    <td>London</td>
    <td>United Kingdom</td>
    <td>nobel.price@universalcancerresearch.org</td>
    <td>10/14/2016</td>
    <td><a href="#">Review</a></td>
    <td>Pending Review</td>
  </tr>
  <tr>
    <td>American Cancer Society</td>
    <td>Atlanta</td>
    <td>Georgia</td>
    <td>tech@cancer.org</td>
    <td>5/24/2015</td>
    <td><a href="#">Review</a></td>
    <td>Pending Review</td>
  </tr>
  <tr>
    <td>Susan G. Komen Breast Cancer Foundation</td>
    <td>Dallas</td>
    <td>Texas</td>
    <td>sue@komen.org</td>
    <td>10/14/2016</td>
    <td><a href="#">Review</a></td>
    <td>Pending Review</td>
  </tr>
  </tbody>
</table> ';
    return $markup;
}

function partnerApplicationSubmissionsData() {
    //Query table and return JSON of "PENDING Review" Applications
    return 'jsonData';
}

function partnerApplicationSubmissionsCount() {
    //Perform SQL to add

    return 2;
}
*/

/**
 * Implements hook_theme().
 */
function icrp_theme() {
    return [
        'my_profile_form' => [
            'render element' => 'form',
        ],
    ];
}

/**
 * Implements hook_form_alter().
 */
/*
function icrp_hook_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
    $form['link'] = array('#markup' => l(t('Link text'),'node'));
    switch ($form_id) {
        case 'user-pass-reset':
            $form['terms_of_use'] = array(
                '#type' => 'checkbox',
                '#title' => t("I agree with the website's terms and conditions."),
                '#required' => TRUE,
            );
            break;
        case 'user_login_block':
            $form['link'] = array('#markup' => l(t('Link text'),'node'));
            break;
        case 'webform_submission_contact_form':
            // Set Type of Issue default value
            $form['elements']['contact_us']['contact_us_container_1']['type_of_issue']['#default_value'] = "Register for CSO Updates";

            // Pre-load user information if available
            $uid = \Drupal::currentUser()->id();
            if($uid > 0 ) {
                $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
                //kint($user);

                $name = $user->get('field_first_name')->value . ' ' . $user->get('field_last_name')->value;
                //drupal_set_message("Name: ". $name);
                $form['elements']['contact_us']['contact_us_container_2']['contact_us_left']['name']['#value'] = $name;

                $email = $user->get('mail')->value;
                $form['elements']['contact_us']['contact_us_container_2']['contact_us_right']['email']['#value'] = $email ;
            }
            break;
    }
    if ($form_id == 'user_form_what') {
        $form['#submit'][] = '_MODULE_goto';
        $form['terms_of_use'] = array(
            '#type' => 'checkbox',
            '#title' => t("I agree with the website's terms and conditions."),
            '#required' => TRUE,
        );
    }
}
*/

function icrp_views_pre_render($view) {
  // Scramble the order of the rows shown on this result page.
  // Note that this could be done earlier, but not later in the view execution
  // process.
  //drupal_set_message("views_pre_render");
  //drupal_set_message("shuffle rows");
  //shuffle($view->result);
  //kint($view);
  /*
  foreach($view->result as $key ){

    $value = $key->_entity->getValue('field_name')->getValue(array(0=>'value'));
    drupal_set_message("$value");
  }
  */
}

function icrp_views_query_alter($view, $query) {

    if($view->id() == 'partner_application_administration_tool_old'){
        $definition = array(
            'table' => 'webform_submission_data',
            'field' => 'sid',
            'left_table' => 'webform_submission',
            'left_field' => 'sid',
        );
        $join = Views::pluginManager('join')->createInstance('standard', $definition);

        $query->addRelationship('webform_submission_data', $join, 'webform_submission');

        // ouptuts "LEFT JOIN {node__field_precise_date} node__field_precise_date ON node_field_data.nid = node__field_precise_date.entity_id AND (node__field_precise_date.deleted = '0' AND node__field_precise_date.langcode = node_field_data.langcode)"

       // $date_format = $query->getDateFormat("node__field_precise_date.field_precise_date_value", "m")." = :value";
        //$query->addWhereExpression(2, $date_format, [":value" => 12]); // Where 12 is the month I need.
    }    
    //\Drupal::logger('hook')->notice('icrp_views_query_alter()');
    //drupal_set_message("views_query_alter");
    //drupal_set_message("View ID: ".$view->id());
    global $user;
    if($view->id() == "partner_application_administration_tool_old") {
        drupal_set_message("You are viewing the Partner Applications");
    }
    //kint($query);
  // (Example assuming a view with an exposed filter on node title.)
  // If the input for the title filter is a positive integer, filter against
  // node ID instead of node title.
  if ($view->id() == 'my_view' && is_numeric($view->exposed_raw_input['title']) && $view->exposed_raw_input['title'] > 0) {
    // Traverse through the 'where' part of the query.
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        // If this is the part of the query filtering on title, chang the
        // condition to filter on node ID.
        if ($condition['field'] == 'node.title') {
          $condition = array(
            'field' => 'node.nid',
            'value' => $view->exposed_raw_input['title'],
            'operator' => '=',
          );
        }
      }
    }
  }
}

function icrp_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

    //drupal_set_message("Form ID: " . $form_id);
    //kint(print_r($form, true));
    switch ($form_id) {
        case 'block_content_basic_edit_form':
            if (strpos($form['info']['widget']['0']['value']['#default_value'],"Partner Home") !== false ||
                strpos($form['info']['widget']['0']['value']['#default_value'],"ICRP Site Updated Date") !== false) {
                if (strpos($form['info']['widget']['0']['value']['#default_value'],"Partner Home Partner Management") !== false) {
                    $blockTitle = "Edit Project Management";
                } else if(strpos($form['info']['widget']['0']['value']['#default_value'],"ICRP Site Updated Date") !== false) {
                    $blockTitle = "Edit Site Updated Date";
                } else if(strpos($form['info']['widget']['0']['value']['#default_value'],"Partner Home") !== false) {
                    $blockTitle = "Edit " . substr($form['#title'],55);
                } else {
                    $blockTitle = "Edit block [" . $form['info']['widget']['0']['value']['#default_value'] . "]";
                }
                unset($form['revision_information']);                     // Remove Revisions section from block edit page
                unset($form['actions']['delete']);                        // Remove Delete button from block edot page
                unset($form['info']);                                     // Remove ablity to edit block title

                $form['body']['widget']['0']['#title'] = $blockTitle;     // Set Block Edit heading
/*
                $form['actions']['cancel'] = array(                       // Add Cancel button
                    '#type'   => 'button',
                    '#value'  => t('Cancel'),
                    '#attributes' => array('onClick' => 'history.go(-1); return true;'),
                    '#weight' => 100,
                );
*/
            }

            break;
        case 'user_register_form':
            //drupal_set_message("user_register_form");
            //\Drupal\icrp\Importer\OrganizationRestClient::populateOrganizations();
            OrganizationRestClient::populateOrganizations();
            break;
        case 'user_login':
        case 'user_login_form':
            //$form['link'] = array('#markup' => t("<div style=padding:20px;'><a href='/user/password'>Forgot Password?</a></div>"));
            break;
    }
}
